### ISSUE TITLE
Implementere bibliotek / parsing av model-dcat-ap no til rdf

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/modelldcatnotordf#1]
Skal kunne høste på følgende format: RDF og alle relevante serialiseringer (turtle, json-ld, rdf/xml etc)
ModellDCAT-AP-NO-spesifikasjonen (høringsutkast): https://informasjonsforvaltning.github.io/modelldcat-ap-no/

OWL: https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/modelldcatno.owl

Akseptansekriterier:

- [ ] Vi skal høste alt fra modelleksempelet og kunne verifisere det med postman/curl eller liknande

Relatert til epos: #489
Modell for testing: https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/model-catalogTestModellDCAT.ttl

- [x] title, identifier, description, theme for modelldcat:informationModel

- [x] foaf:agent publisher

- [x] title, identifier for  modelldcat:modelElement

- [x] Oppsett bibliotek

![ModellDCAT-ap-no](https://user-images.githubusercontent.com/34306822/97409591-31ba8800-18fe-11eb-981f-4c8a4f39869f.png)

**Comment by frederik-ronnevig** [comment]
Rettet litt på lenken i beskrivelsen fra : 

https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/dcatno_informationModel_en.owl

til riktig lenke:

https://github.com/Informasjonsforvaltning/modelldcat-ap-no/blob/master/ontology/modelldcatno.owl

Antar at dette er riktig, ikke sant? :-) Den første var død..

**Comment by lillelars** [comment]
Første versjon av biblioteket er nå ferdig. støtter ModelDCAT-AP-NO
