### ISSUE TITLE
Huskeliste ved eventuell implementasjon av validator : Endring av valideringsregler ved oppdatering fra modelldcatno 1.0 til 1.1

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/modelldcatnotordf#194]
**Forhold som endrer valideringsregler ved oppdatering fra modelldcatno 1.0 til 1.1**

- [ ] Modellelement: identifikator - dct:identifier - Endret fra obligatorisk til anbefalt - Strengt For strengt å ha dette som en obligatorisk egenskap når modellelementene som RDF-ressurser i tillegg tildeles egne URI’er.

- [ ] Modellelement: identifikator - dct:identifier - Multiplisitet endret fra 1..1 til 0..1 - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Kodeelement: kode - skos:notation - Multiplisitet endret fra 0..1 til 1..1 - Som følge av at kravsnivå endres fra anbefalt til obligatorisk.

- [ ] Kodeelement: kode - skos:notation - Endret fra valgfri til obligatorisk - Det bør være et krav at et kodeelement har en kode som kan brukes i et datafelt.

- [ ] Kodeelement: identifikator - dct:identifier - Multiplisitet endret fra 1..1 til 0..1 - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Kodeelement: identifikator - dct:identifier - Endret fra obligatorisk til anbefalt - For strengt å ha dette som en obligatorisk egenskap når kodeelementene som RDF-ressurser i tillegg tildeles egne URI’er.

- [ ] Kodeelement: i kodeliste - skos:inScheme - Multiplisitet endret fra 0..n til 1..n - Skrivefeil i forrige versjon. Det bør være et krav at et kodeelement tilhører minst en kodeliste, slik at man unngår at modellene inneholder kodeelementer uten tilhørighet.

- [ ] Kodeelement: anbefalt kodetekst - skos:prefLabel - Multiplisitet endret fra 1..n til 0..n - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Kodeelement: anbefalt kodetekst - skos:prefLabel - Endret fra obligatorisk til anbefalt - Det er ikke alle kodeelementer som har en anbefalt kodetekst knyttet til seg. For eksempel vil UML enumerasjoner inneholde bare kodeverdier.

- [ ] Informasjonsmodell: tema - dcat:theme - Multiplisitet endret fra 1..n til 0..n - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Informasjonsmodell: tema - dcat:theme - Endret fra obligatorisk til anbefalt - For strengt å ha dette som en obligatorisk egenskap. Det er ikke alle virksomheter som har kategorisert modellene sine etter tema.

- [ ] Informasjonsmodell: identifikator - dct:identifier - Multiplisitet endret fra 1..1 til 0..1 - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Informasjonsmodell: identifikator - dct:identifier - Endret fra obligatorisk til anbefalt - For strengt å ha dette som en obligatorisk egenskap når egenskapene som RDF-ressurser i tillegg tildeles egne URI’er.

- [ ] Informasjonsmodell: beskrivelse - dct:description - Multiplisitet endret fra 1..n til 0..n - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Informasjonsmodell: beskrivelse - dct:description - Endret fra obligatorisk til anbefalt - For strengt å ha dette som en obligatorisk egenskap. Flere virksomheter har ikke tekstlige beskrivelser av modellene sine.

- [ ] Egenskap: identifikator - dct:identifier - Multiplisitet endret fra 1..1 til 0..1 - Som følge av at kravsnivå endres fra obligatorisk til anbefalt.

- [ ] Egenskap: identifikator - dct:identifier - Endret fra obligatorisk til anbefalt - For strengt å ha dette som obligatorisk når egenskapene som RDF-ressurser i tillegg tildeles egne URI’er.

- [ ] Krav til bruk av kontrollerte vokabularer - For egenskap dct:type i klassen modelldcatno:InformationModel - dct:type - Nytt kontrollert vokabular, Modelltyper, som skal brukes for egenskapen dct:type i klassen Informasjonsmodell (modelldcatno:InformationModel) - Egenskapen har manglet et kontrollert vokabular.

- [ ] Krav til bruk av kontrollerte vokabularer - For egenskap dct:spatial - dct:spatial - "Administrative enheter" fra Kartverket anbefalt brukt - Fordi EU-vokalubarer som skal brukes, ikke inneholder norske administrative enheter som fylker og kommuner.

**Comment by KjerstiSteien** [comment]
Lukkes da dette er et bibliotek som ikke brukes aktivt.
