### ISSUE TITLE
Flere nøstede blanke noder serialiseres ikke riktig

### ISSUE THREAD

**Issue by frederik-ronnevig** [Informasjonsforvaltning/modelldcatnotordf#73]
- [x] Sette opp et draft PR

- [x] presentere / diskusjonsforum / slaktefest 30 min

- [x] Hente baseurl fra environment-variabel
- [x] Refaktorere til å gjøre Skolemizer tilstandsløs og global - uavhengig av informasjonsmodell
- [x] Endre skolemiseringslogikken slik som beskrevet på W3C
- [x] Legge Skolemizer i egen modul
- [x] Ta i bruk skolemizer på samtlige noder - rette alle tester med blank nodes
- [x] Fjerne alle referanser til blanke noder

Kommentarer fra Architect:

> Proposal: https://www.w3.org/2011/rdf-wg/wiki/Skolemisation
> 
> I tillegg kan det vere nyttig å studere denne PR over at the RDF4J HQ: https://github.com/eclipse/rdf4j/pull/955/files
> 
> Sjå spesifikt metoden createNode() litt nede i PR.

Original problemstilling:

@matsjs  har funnet en feil som er gjennomgående ikke bare i mitt bibliotek men muligvis også i @stigbd sitt dcat-bibliotek. Det ser ut som om det er alle tilfeller der det er flere nøstende noder som alle er blank nodes:

```
    datatype1 = DataType()
    attribute = Attribute()
    datatype2 = DataType()
    datatype1.has_property.append(attribute)
    attribute.has_data_type = datatype2
    datatype2.title = {"nb": "Tittel på datatype 2"}
```

Burde gi:

```
[] a ns2:DataType ;
    ns2:hasProperty [ a ns2:Attribute ;
            ns2:hasDataType [ a ns2:DataType ;
                    ns1:title "Tittel på datatype 2"@nb ] ] .
```

Men gir i stedet:

```
[] a ns2:DataType ;
    ns2:hasProperty [ a ns2:Attribute,
                ns2:DataType ;
            ns1:title "Tittel på datatype 2"@nb ;
            ns2:hasDataType [ ] ] .
```

Feilen skjer antakelig når vi legger til alle triplene ved serialisering av en node som igjen har subproperties.
